version: "2"

linters:
  default: all
  disable:
    - exhaustruct
    - depguard
    - wrapcheck
    - tagalign
    - forbidigo
    - perfsprint
    - gochecknoglobals
    - wsl  # deprecated
    - revive  # too noisy
    # Legacy code suppressions:
    - cyclop  # cyclomatic complexity
    - errcheck  # unchecked errors
    - nakedret  # naked returns
    - nlreturn  # blank lines before return
    - noctx  # exec.Command vs CommandContext
    - noinlineerr  # inline error handling
    - modernize  # interface{} -> any
    - staticcheck  # tagged switch suggestions
    - gosec  # security issues (legacy code)
